def ReadTagsInFileHold():
    tagsDic = {'A': 'Analog Signal', 'FO': 'Fial Open', 'LSLL': 'Level Switch Low for Level Below LSL', 'RC': 'Ratio Controller',
          'AC': 'Analysis Controller', 'FQ': 'Flow Indicator Totaliser', 'LT': 'Level Transmitter', 'RTD': 'Resistance Temperature Detector',
          'AAH': 'Analysis Alarm [High]', 'FQI': 'Flow Indicator with Total Counter', 'LY': 'l/P Converter [Level Loop]',
          'RTU': 'Remote Terminal Unit', 'AAHL': 'Analysis Allarm [High/Low]', 'FR': 'Flow Recorder', 'LO': 'Lock Open','s': 'Solenoid',
          'AAL': 'Analysis Allarm [Low]', 'FRC':'Flow Recorder Controller', 'MCC': 'Motor Control Center', 'SAH': 'Speed Alarm [High]',
          'AS': 'Air Supply	FRT	Flow Recorder Transmitter', 'MTU': 'Master Terminal Unit', 'SAHL': 'Speed Alarm [High/ Low]',
          'ASDH': 'Analysis Shutdown [High]', 'FS':	'Flow Switch', 'NC': 'Normally Closed', 'SAL': 'Speed Alarm [Low]',
          'ASDL': 'Analysis Shutdown [Low]', 'FSDH': 'Flow Shutdown [High]', 'NO':	'Normally Open', 'SC': 'Sample Connection',
          'ASH': 'Analysis Switch [High]', 	'FSDL':	'Flow Shutdown [Low]', 'p': 'Pneumatic Signal', 'SD': 'Shutdown Panel',
          'ASHL': 'Analysis Switch [High/Low]', 'FSH': 'Flow Switch [High]', 'PAH': 'Pressure Alarm [High]', 'SI': 'Speed Indicator',
          'ASL': 'Analysis Switch [Low]', 'FSL': 'Flow Switch [Low]', 'PAHL': 'Pressure Alarm [High/Low]', 'SR': 'Speed Recorder',
          'AT': 'Analysis  Transmitter', 'FT': 'Flow Transmitter', 'PAL': 'Pressure Alarm [Low]', 'SS': 'Steam Supply','BC': 'Burner Controller',
          'FY': 'Computer.Relay, Amplifier or l/P', 'PB': 'Pushbutton', 'SSH': 'Speed Switch [High]', 'BAH': 'Burner Alarm [High]',
          'PC': 'Pressure Controller', 'SSHL': 'Speed Switch [High/Low]', 'BAHL': 'Burner Alarm [High/Low]', 'GS': 'Instrument Gas Supply',
          'PCV': 'Pressure Control Valve', 'SSL': 'Speed Switch [Low]', 'BAL': 'Burner Alarm [Low]', 'H': 'Hydraulic',
          'PD': 'Pulsation  Dampener', 'TAH': 'Temperature Alarm [High]', 'BDV': 'Blowdown Valve', 'HMV': 'Hydraulic Motor Operated Valve',
          'PDA': 'Pressure  DifferentialAlarm', 'TAHL': 'Temperature Alarm [High/Low]', 'BPR': 'Back Pressure Regulator',
          'HOA': 'Hand/Off/Auto Switch', 'PdAH': 'Pressure  DifferentialAlarm [High]', 'TAL': 'Temperature Alarm [Low]',
          'BS': 'Burner Switch', 'HS': 'Hand Switch', 'PdAL': 'Pressure Differential Alarm[Low]', 'TC': 'Temperature  Controller',
          'BSH': 'Burner Switch [High]', 'I': 'Current Signal', 'Pdl':	'Pressure Differential Indicator', 'TCV': 'Temperature Control Valve',
          'BSHL': 'Burner Switch [High/Low]', 'l/ F': 'Interface', 'PdIC': 'Pressure DifferentialIndicator Controller',
          'TD': 'Time Delay', 'BSL': 'Burner Switch [Low]', 'I/I': 'Current Indicator', 'PdS': 'Pressure DifferentialSwitch',
          'TE': 'Temperature [Measuring] Element/Thermocouple', 'BS&W': 'Basic Sediment and Water', 'l/P': 'Current to Pneumatic',
          'PdSH': 'Pressure Differential Switch [High]', 'TF': 'Temperature Gage', 'CCP':'Central Control Panel',
          'I/PA': 'Current to Pneumatic Alarm', 'PdSL': 'Pressure DifferentialSwitch [Low]', 'TH': 'Thermostat',
          'CDS': 'Compressor Shutdown', 'Kl': 'Clock/Timer', 'PG': 'Pressure Gage', 'Tl': 'Temperature  Indicator',
          'CFA': 'Common Fault Alarm', 'LA': 'Level A larm', 'P/I': 'Pneumatic To Current Converter',
          'TIC': 'Temperature Indicator Controller', 'COR': 'Corrosimeter', 'LAH': 'Level A larm [High]', 'Pl': 'Pressure Indicator',
          'TIT': 'Temperature Indicator Transmitter', 'csc': 'Car Seal Close', 'LAHH': 'Level A larm High for Level Above',
          'LAH': 'PIC	Pressure Indicator Controller', 'TJI': 'Multipoint Temperature Indicator/Thermocouple',
          'cso': 'Car Seal Open', 'LAHL': 'Level A larm [High/Low]', 'PIT': 'Pressure Indicator Transmitter', 'TR': 'Temperature Recorder',
          'CV': 'Control Valve', 'LAL': 'Level A larm [Low]', 'PJI': 'Multipoint Pressure Indicator', 'TRC': 'Temperature  Recorder Controller',
          'E/I': 'EMF to Current Converter', 'LALL': 'Level A larm Low for Level Above LAL', 'PJR': 'Multipoint Pressure Recorder',
          'TRT': 'Temperature Recorder Transmitter', 'ES': 'Electrical Switch', 'LC': 'Level Controller', 'POV': 'Pneumatically Operated Valve',
          'TSDH': 'Temperature Shutdown [High]', 'ESD': 'Emergency Shutdown Station', 'LCV': 'Level ControlValve', 'PR': 'Pressure Recorder',
          'TSDL': 'Temperature Shutdown [Low]', 'ESDV': 'Emergency Shutdown Valve', 'LG': 'Level Gauge', 'PRC': 'Pressure Recorder Controller',
          'TSH': 'Temperature Switch [High]', 'FAL': 'Flow Alarm Low', 'LI': 'Level Indicator', 'PRT': 'Pressure Recorder Transmitter',
          'TSHL': 'Temperature  Switch[High/Low]', 'FAH': 'Flow Alarm High', 'LIC': 'Level Indicator Controller',
          'PRV': 'Pressure Regulating Valve', 'TSL': 'Temperature   Switch[Low]', 'FAHH': 'Flow Alarm High For Level Above FAH',
          'LIT': 'Level Indicator Transmitter', 'PSDH': 'Pressure Shutdown [High]', 'TT': 'Temperature  Transmitter',
          'FAHL': 'Flow Alarm [High/Low]', 'LLH': 'Liquid Level [High]', 'PSDL': 'Pressure Shutdown [Low]',
          'TW': 'Thermowell', 'FALL': 'Flow Alarm Low For Level BelowFAL', 'LLL': 'Liquid Level [Low]', 'PSE': 'Rupture Disk',
          'TY': 'Computer. Relay,Converter.etc.in Temp. Loop', 'FC': 'Flow Controller', 'LLN': 'Liquid Level [Normal]',
          'PSH': 'Pressure Switch [High]', 'us': 'Utility Station', 'FC': 'Fail Close', 'LO': 'Lock Closed Whenby amanual Valve',
          'PSHH': 'Pressure Switch High tor PressureAbovePSH', 'VAH': 'Vibration Alarm [High]', 'FCV': 'Flow Control Valve',
          'LR': 'Level Recorder', 'PSHL': 'Pressure Switch [High/ Low]', 'VSDH': 'Vibration Shutdown[High]', 'FE': 'Flow Element',
          'LS':	'Level Switch', 'PSL': 'Pressure Switch [Low]', 'VSH': 'Vibration Switch [High]', 'FFA': 'Flame Failure Alarm',
          'LSDH': 'Level Shutdown [High]', 'PSLL': 'Pressure Switch Low tor Pressure Below PSL' , 'ws': 'Water Supply',
          'FFSD': 'Flame Failure Shutdown', 'LSDL': 'Level Shutdown [Low]', 'PSV': 'Pressure Safety Valve', 'x': 'Multiply',
          'FG': 'Flow Gage/Flow Sight Glass', 'LSH': 'Level Switch [High]', 'PT': 'Pressure Transmitter', 'zc': 'Position Switch [Closed]',
          'Fl': 'Flow Indicator', 'LSHL': 'Level Switch [High/Low]', 'POS': 'Positioner', 'zo': 'Position Switch [Open]',
          'FIC': 'Flow Indicator Controller', 'LSL': 'Level Switch [Low]', 'PY': 'Relay,Computer. Amplifier. Converter or',
          'FIT': 'Flow Indicator Transmitter', 'LSHH': 'Level Switch High for LevelAbove LSH'}
    tagslist = ['A', 'FO', 'LSLL', 'RC', 'AC', 'FQ', 'LT', 'RTD', 'AAH', 'FQI', 'LY', 'RTU', 'AAHL', 'FR', 'LO', 's',
                'AAL', 'FRC', 'MCC', 'SAH', 'AS', 'MTU', 'SAHL', 'ASDH', 'FS', 'NC', 'SAL', 'ASDL', 'FSDH',
                'NO', 'SC', 'ASH', 	'FSDL', 'p', 'SD', 'ASHL', 'FSH', 'PAH', 'SI', 'ASL', 'FSL', 'PAHL', 'SR',
                'AT', 'FT', 'PAL', 'SS','BC','FY', 'PB', 'SSH', 'BAH', 'PC', 'SSHL', 'BAHL', 'GS', 'PCV', 'SSL',
                'BAL', 'H', 'PD', 'TAH', 'BDV', 'HMV', 'PDA', 'TAHL', 'BPR', 'HOA', 'PdAH', 'TAL', 'BS', 'HS', 'PdAL'
                'TC', 'BSH', 'I', 'Pdl', 'TCV', 'BSHL', 'l/ F', 'PdIC', 'TD', 'BSL', 'I/I', 'PdS', 'TE' , 'BS&W',
                'l/P', 'PdSH', 'TF', 'CCP', 'I/PA', 'PdSL', 'TH', 'CDS', 'Kl', 'PG', 'Tl', 'CFA', 'LA', 'P/I', 'TIC',
                'COR', 'LAH', 'Pl', 'TIT', 'csc', 'LAHH', 'LAH', 'TJI', 'cso', 'LAHL', 'PIT', 'TR', 'CV', 'LAL', 'PJI',
                'TRC', 'E/I', 'LALL', 'PJR', 'TRT', 'ES', 'LC', 'POV', 'TSDH', 'ESD', 'LCV', 'PR', 'TSDL', 'ESDV', 'LG',
                'PRC',  'TSH', 'FAL', 'LI', 'PRT', 'TSHL', 'FAH', 'LIC',  'PRV', 'TSL', 'FAHH', 'LIT', 'PSDH', 'TT',
                'FAHL', 'LLH', 'PSDL', 'TW', 'FALL', 'LLL', 'PSE', 'TY', 'FC', 'LLN', 'PSH', 'us', 'FC', 'LO', 'PSHH',
                'VAH', 'FCV', 'LR', 'PSHL', 'VSDH', 'FE',  'LS', 'PSL', 'VSH', 'FFA', 'LSDH', 'PSLL' , 'ws', 'FFSD',
                'LSDL', 'PSV', 'x', 'FG', 'LSH', 'PT', 'zc', 'Fl', 'LSHL', 'POS', 'zo', 'FIC', 'LSL', 'PY', 'FIT','LSHH']
    return tagslist


